fdsc.user.js

1. Use (Grease|Tamper)Monkey's storage to keep the token, thereby removing the need to auth on 150-some sites.
2. To do that, remove the injection technique and just run it as a 'normal' script. Otherwise the `GM_*` functions just don't work.

This might actually work

---

fdsc.user.js

This is more or less a 'last resort' update to FDSC to a working version until a version that correctly handles MS auth exists.
Currently, Tampermonkey doesn't safely process the lack of a 'download URL' and 'update URL' item when we manually update the script after installation.  It's still force-updating to broken versions in some cases, so we ultimately have a few issues as a result of that.
We also have new users setting up FDSC with 1.2.1, which doesn't work.  These commits replace the 1.2.1 code with the code from 0.14.1, but version bumps to 1.2.2 to make sure everyone gets this update.
It's a drastic commit/change, but ultimately will solve the problem of "not working" until the MS auth issue is solved.

Revert FDSC code base to 0.14.1, list as 1.3.1

---

fdsc.user.js

No version bump was done so these changes are not caught by userscript update functions.  Bump version accordingly.
See #10 for what prompted the last commit, and why I'm making this PR to actually do the version bump (which was *not* done previously)

Version bump (to 1.4.2) as a result of fix for #10

---

gas-mask-se.user.js

Also, enabled for HTTPS sites even though Smokey doesn't seem to ever post these. Also, experimental change to delay showing the gas mask picture

Gas mask 1.2 - make it always active for now

---

fdsc.user.js

Exclude Area51 from the list of things FDSC works on.  It's weird with MetaSmoke, so just disable FDSC for this for now (per @ArtOfCode as well)

Exclude Area51, it doesn't like FDSC or MetaSmoke

---

gas-mask-se.user.js

This ensures that it isn’t blurry on Retina screens.

Use an SVG image for GasMask

---

index.html
userscripts.js

This adds a GitHub pages website, which should be accessible at https://charcoal-se.org/Userscripts/ once merged.
Before merging:

Add website

---

aeks.user.js

Updating AEKS to gracefully handle sites where the user has no account.
The moment you create an account, AEKS will enable keyboard shortcuts, meaning that when you go back to the reported post, shortcuts can be used.

Account for sites where the user has no account

---

autoflagging.css

Don't show 2 lines for deleted ("handled") reports,
Expand them again on hover.
What do you think, @Glorfindel83 / @j-f1?

Collapse "deleted" reports

---

autoflagging/autoflagging.user.js
metapi/metapi.js

@ArtOfCode- / @Glorfindel83  please review:
I moved the ReconnectingWebSocket usage to metapi and implemented metapi for the websocket in AIM.
The code dealing with `pendingSockets` is to allow other scripts to call `metapi.watchSocket`, even if `ReconnectingWebSocket` isn't loaded yet.
`watchSocket` now also allows for a close handler to be passed.

metapi reconnectingSocket, AIM: use metapi

---

spamtracker/spamtracker.css
spamtracker/spamtracker.meta.js
spamtracker/spamtracker.user.js

This pull request adds my Spamtracker userscript to the global charcoal userscript repo.
The purpose of this userscript is to alert charcoal users using sound and a desktop notification of new Smokedetector messages that require their attention, it by default uses the meta SE sound, but this can be configured when pressing the link in the footer of the chat page. This userscript can be compared to the Spamtracker Google Chrome extension, that Normal Human had made, but got removed for unknown reasons.
[I already have agreed to license my past and future contributions under MIT/Apache-2.0](https://github.com/Charcoal-SE/userscripts/issues/40#issuecomment-280845682)

Add Spamtracker from https://github.com/ferrybig/SpamTrackerReboot.git

---

autoflagging/autoflagging.meta.js
autoflagging/autoflagging.user.js
fdsc/fdsc.meta.js
fdsc/fdsc.user.js
sds/sds.meta.js
sds/sds.user.js
spamtracker/spamtracker.meta.js
spamtracker/spamtracker.user.js

This uses npm’s [`debug`](https://www.npmjs.com/package/debug) module to manage logging.

Use debug from npm instead of custom debug solutions

---

fire/fire.user.js

Resolves issue #91, details can be found there.

Fixed max char length for metasmoke token

---

fire/fire.user.js

I added a `closePopup()` call to the callback on the save button, which seems to resolve issue #87, although you may want tot move the call to somewhere which makes more sense. I don't really know the codebase.

Resolved blur not disappearing when save button clicked

---

fire/fire.user.js

This at least lets us see the posts and provide feedback.
There is a mix of API v1 and API v2.0, as some things in V2.0 appear to be broken.
It's still missing showing the user that they have already given feedback (when the feedback is from FIRE), because the feedback entry created from FIRE only includes the MS user ID, not the username (which is what is checked). I'll look into it, but figured it's better to get people something that will at least basically work.

Partial use of API v2.0; Restore primary functionality.

---

gas-mask-se/gas-mask-se.user.js

This makes sense because there won't be spam on channels, and not excluding it will block community from posting images (which happens at the beginning of a channel)

Exclude gasmask from channels

---

fire/fire.user.js

It's already covered in two places: Smokey and AIM. Also, FIRE always shows `undefined` for this so it's currently useless.

Remove reason weight display from FIRE

---

fire/README.md
fire/fire.meta.js
fire/fire.user.js

Block keypress from getting to chat input (again).
Update text response expected from MS when the flag option isn't present ("probably deleted").

FIRE 1.0.31

---

autoflagging/autoflagging.meta.js
autoflagging/autoflagging.user.js

This is due to Smokey now adding reason weight in report messages and consequently invalidating the current regex. Adding the part that catches the reason weight solves this issue.
Example on [Regex101](https://regex101.com/r/PzaDCp/1).

Fix batch report not detected in AIM

---

sim/sim.user.js

Display 'No Feedback' when there's no feedback
Improve attaching. Attach to posts:
earlier in page load
after inline edits
after other page modification
on NATO w/ and w/o NATO Enhancements
handle the .post-menu-container which SE may, or may not, use
in review queues
in close-vote popups

SIM: Version 0.5.1

---

autoflagging/autoflagging.meta.js
autoflagging/autoflagging.user.js

AIM: Version 0.31
* Use shrink-fade CSS from SOCVR's URRS for .ai-deleted.
* Additional CSS and JS changes to reduce display conflict with timestamp.

AIM: Version 0.31: use shrink fade CSS for .ai-deleted

---

fire/package-lock.json
fire/package.json
metapi/package-lock.json
metapi/package.json
ms-dark-theme/package-lock.json
ms-dark-theme/package.json
package-lock.json
package.json
review-keyboard-shortcuts/package-lock.json
review-keyboard-shortcuts/package.json
sim/package-lock.json
sim/package.json

This updates `xo` to 0.50.0 and `eslint` to 8.18.0 along with a general `npm update`.
There are a couple of new/changed `eslint` rules which are disabled for FIRE and metapi in order to maintain compatibility with the current code. As with all of these updates, the individual packages should determine what they want the eventual settings to be.

Update dependencies: xo to 0.50.0 and eslint to 8.18.0

---

sim/package-lock.json
sim/package.json
sim/sim.user.js

This makes the "smokey" quicklink added by the script into a proper link (by changing it from a `<button>` element into an `<a>` element). The styling and normal behavior both remain unchanged. Instead of behaving like the built-in "close" and "flag" quicklinks (which are `<button>` elements and only have an associated pop-up), the "smokey" quicklink now behaves like the built-in "share" and "edit" quicklinks. When clicked normally, the pop-up is displayed. When clicked with a meta key depressed and/or invoked with a context menu, it now works like a normal link, going to the associated MS page for the post. Obviously, if the post has not been reported to MS, then the link will not do anything useful, so this is a much less generally useful way of interacting with the "smokey" quicklink, …

SIM: Make "smokey" quicklink a proper link (in addition to its normal function as a button)

---

sim/package-lock.json
sim/package.json
sim/sim.user.js

This PR:
* Adds buttons for moderators which allow the moderator to undelete, report, and re-delete, as their choice of spam, R/A, or mod-delete, automatically with waiting for the post to be reported to metasmoke to be sure that SD has all the data and re-deleting is OK.
* If the post is not deleted, then it indicates when the report has gotten to MS, so that any additional actions can be taken without causing SD to not get the data.
* An additional delay, currently 3 seconds, is added after MS has the data in order to make sure that SD is watching for deletion. Issue noticed/reported by Ryan M.
* Better error handling for some cases.

SIM: Version 0.8.0: add moderator buttons for undelete, report, redelete (as spam, R/A, mod; user's choice)

---

fire/README.md
fire/fire.meta.js
fire/fire.user.js

FIRE 1.6.0:
* Alt-Click copies selection or URL for link clicked on to chat input
* Use placeholder URL for placeholder image links to prevent link pre-fetch, which is done under some conditions
* improve post rendering
* tags, `<kbd>` , CSS for placeholder images, GitHub oneboxes (just link, because more info isn't in the data)

FIRE 1.6.0 Alt-Click copies to chat input, use placeholder URL for placeholder image links, and improve post rendering

---

fire/README.md
fire/fire.meta.js
fire/fire.user.js
fire/package-lock.json
fire/package.json

This adapts to the additional data SE is now sending with the `access_token` when using the implicit OAuth 2.0 flow with the SE API.

FIRE 1.6.1

---

fire/README.md
fire/fire.meta.js
fire/fire.user.js

This removes the use of the `DOMSubtreeModified` event, which has been deprecated for a very long time, and which is scheduled for removal from Chrome in the very near future ([Chrome 127, on 2024-07-30](https://chromestatus.com/feature/5083947249172480)).

FIRE 1.6.2: remove DOMSubtreeModified
