Charcoal-SE/userscripts

fdsc.user.js

Adds the naa count to the bottom of the dialogue

Added naa counter

---

README.md
spam_reporter.user.js

I modified the script originally created by TinyGiant [here](https://github.com/Tiny-Giant/myuserscripts/blob/d73d3fd4a41700c502626dd2e2482e8e3eef1a23/SpamReporter.user.js), so that it works in Charcoal HQ.
Full credit goes to TinyGiant. And before you ask, yes, we have permission to redistribute the modified script in our own repo.
I also added a readme to the repo.

Spam reporter script

---

fdsc.user.js
spam_reporter.user.js

New features:
- Auto-update
- Link now has hover text
- Button has been moved between the share and edit buttons so you don't click it by accident
---
I also made a small fix to FDSC, the description will now show correctly.
(as a side effect, Atom seems to have automatically collapsed the whitespace-only lines, sorry about that, it should have no effect on functionality. )

Added auto-update and moved button for reporter script

---

spam_reporter.user.js

Just realised my mistake, the edit button has a different class depending on whether or not you are logged in, and whether or not you have full edit privileges. 
Now, the button should appear second in the list, no matter what buttons are present.

Minor fix of spam reporter

---

gas-mask-se.user.js

Replaces (reversibly via a click) all post images in posts linked by Smokey.

Project gas mask - make flagging safe again

---

gas-mask-se.user.js

remove unnecessary require; detach timer when no longer needed

Gas mask 1.1 - minor bugfixes

---

fdsc.user.js

This delays the decision whether to send feedback or not until the Ajax call to check if the post has been reported by Smokey has finished. See http://chat.stackexchange.com/transcript/message/34174179#34174179

Fix the error with feedback not being sent if the Ajax call hasn't finished yet

---

hideads.user.js

Solves the problem mentioned [here](http://meta.stackexchange.com/q/289895/295232); the top bar ad is not displayed anymore so the content of the page (including the mighty `flag` link) doesn't scroll down as the ad is being displayed.

Initial version of the Hide Ads userscript

---

autoflagging.user.js

Just testing for the moment; will merge when confirmed working

Swap names and flag icon

---

gas-mask-se.user.js

`document.head.append` is `undefined`, use `document.head.appendChild` instead.

GasMask: load styles

---

autoflagging.user.js

Use a Unicode character to indicate that a post has been autoflagged, instead of an image.

Emoji status

---

autoflagging.css
autoflagging.user.js
fdsc.user.js
gas-mask-se.user.js
hideads.user.js
ms_dark_theme.user.js
package.json
userscripts.js

This uses the [xo](https://github.com/sindresorhus/xo) style.
Since lots of stuff was changed, I’m waiting to make sure everyone agrees.
Fixes #37.

Use xo code style

---

userscripts.js

https://github.com/Charcoal-SE/charcoal-se.github.io/issues/10#issue-209153910
Closes Charcoal-SE/charcoal-se.github.io#10.

small error, (should) fix issue #10 on the website repo

---

fdsc.user.js

Add a "Confirm Autoflag" button to FDSC

---

fire/README.md

```diff
To send _"False positive"_ feedback:
1. <kbd>Ctrl</kbd>+<kbd>Space</kbd> - Open the last report,
-2. <kbd>1</kbd> - Select _"False positive"_,
+2. <kbd>4</kbd> - Select _"False positive"_,
3. <kbd>Space</kbd> or <kbd>Enter</kbd> - Submit.
```

Did you mean: Press 4 to select "False Positive"

---

fdsc.user.js

Added a | get write token" button to the flag dialog. Also accessible on the dialog on deleted posts.

"Get write token" button

---

autoflagging/autoflagging.user.js

This pull request depends on the following MS API bug being fixed:
Charcoal-SE/metasmoke#143
Fixes #65.

Load more reasons for SD messages

---

.on-save.json
fire/fire.user.js
fire/fire.user.md
fire/package.json
jsdoc2md/separator.hbs

Automatically generate markdown files for your `userscript.user.js` on save.
Requires [jsdco2md](https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/How-to-use-with-npm-run) to be installed, together with the [Atom "on-save" package](https://atom.io/packages/on-save).  
Once you have this installed, copy an existing command in `.on-save.json` to a new entry in the array, and specify the required file name in `files`.
Then, `userscript.user.md` will automatically be generated when you save `userscript.user.js`.

Js doc parser

---

fire/fire.user.js

EmojiOne 3.0 Release 
The 3.0 release brings about many breaking changes, please see the README for a complete description. Changes include splitting of the image assets into their own repo, merging the emoji-alpha-codes repo, and a largely restructured emoji.json file. Be sure to review the new licensing structure for image assets as well. 
see: https://github.com/Ranks/emojione-assets

updated image path

---

README.md

Adding SpamTracker by Ferrybig to the README: https://github.com/Charcoal-SE/userscripts/pull/74

Add spam tracker to readme

---

extractScriptMetadata.sh

Avoid the [common antipattern](http://www.iki.fi/era/unix/award.html#grep) and reimplement the entire script in Awk instead.

extractScriptMetadata.sh: replace sed | awk with awk

---

autoflagging/autoflagging.meta.js
autoflagging/autoflagging.user.js
fire/fire.meta.js
fire/fire.user.js

Added support for the SOBotics chatroom, since Smokey is now running there too.

added SOBotics chatroom

---

fire/README.md
fire/fire.meta.js
fire/fire.user.js

Now in it's own PR:
This should provide a fix for images being displayed in code tags by escaping them.

Fire: Fix for #90

---

.gitignore
fire/README.md
fire/fire.meta.js
fire/fire.scss
fire/fire.user.js

Add room 58631: The Restaurant at the End of the Universe.
Adjust CSS (MS button position, blockquote, li, version and settings button location).
Add `toastr` message for other MS flagging responses.
Use String.fromCodePoint for special characters to prevent editing issues.
Fix issue: After getting MS token, remove blur open the current report popup.
Fixes #90 (thanks @geisterfurz007)

FIRE 1.1.0: Enable on chat transcripts, searches and user pages; various adj.

---

charcoal-autocomments/comments.js

Updated the license link to version 4.0, updated the Be Nice policy link to the Code of Conduct, and made some grammar improvements.

Link to 4.0 license; grammar improvements

---

fire/fire.user.js

That way, FIRE can be used to review the "feedback received" messages.

[FIRE] Recognize messages from the new metasmoke account

---

fire/README.md
fire/fire.meta.js
fire/fire.user.js
fire/package.json

FIRE: version 1.3.0:
- Add detection of "feedback received" messages from metasmoke user
- Add additional rooms

FIRE: version 1.3.0: Add detection of "feedback received" messages from metasmoke user

---

autoflagging/autoflagging.meta.js
autoflagging/autoflagging.user.js

Bug fixes:
* NAA symbol
* Not displaying usernames for feedback matching the default type, but without a "-"
Quite a warning about unneeded `eslint` disable.

AIM version 0.29

---

fire/README.md
fire/fire.meta.js
fire/fire.user.js

* Make short links more visible
* Recognize "obfuscated" as a type of number detection.
* Improve linkification of bare URLs in parts of `why` data.
* Add loading via bookmarklet and manual transfer of data from chat.SE to chat.SO and chat.MSE to the README.md file.

Fire Version 1.5.0

---

sim/sim.user.js

* Adapt to SE changes from a while back
* Post menu changes which affect normal pages and NATO
* More efficient exclusion of pages on which running is ineffective
* Get the correct SE API site parameter for localized SO sites

SIM version 0.6.2

---

fire/README.md
fire/fire.meta.js
fire/fire.user.js
fire/package-lock.json
fire/package.json
metapi/package-lock.json
metapi/package.json
ms-dark-theme/package-lock.json
ms-dark-theme/package.json
package-lock.json
package.json
review-keyboard-shortcuts/package-lock.json
review-keyboard-shortcuts/package.json
sim/package-lock.json
sim/package.json

* FIRE version 1.5.1:
* handle SmokeDetector using bold formatting for the post title
* Update dependencies

FIRE version 1.5.1 and update dependencies

---

sim/package-lock.json
sim/package.json
sim/sim.user.js

This adds the option to post a `!!/report` in Charcoal HQ for the post, if no report is found in MS and the post isn't deleted.

SIM: Version 0.7.0: add option to report the post when there is no report found

---

sim/package-lock.json
sim/package.json
sim/sim.user.js

SIM: version 1.8.1:
* Change the MS API endpoint being used in order to work on meta sites and localized SO sites (i.e. all sites with a "." in their API parameter).
* Change to using Semantic Versioning 2.0.0 (i.e. use a 1 in the major release position to indicate it's been released)
* Some code cleanup

SIM: version 1.8.1: fix on meta and localized SO sites

---

fdsc/fdsc.meta.js
fdsc/fdsc.user.js

- Updated to support new flag popup, jQuery 3.0, MutationObserver
- Toast messages for Metasmoke calls restored
- Works in review queues as well now
- Authentication code popup is not hidden behind flag dialog anymore

FDSC v1.20
